linters:
  enable:
    - gci
    - gofmt
    - gosec
    - unconvert

linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log

  gci:
    local-prefixes: github.com/coord-e/epgstation_exporter
