on: [push, pull_request]

name: ci

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - run: make build
  lint:
    name: golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.49'
