on: [push, pull_request]

name: ci

jobs:
  build:
    name: build
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux]
        arch:
          - amd64
          - arm
          - arm64
    env:
      GOOS: '${{ matrix.os }}'
      GOARCH: '${{ matrix.arch }}'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - run: make build RELEASE=1
      - uses: actions/upload-artifact@v3
        with:
          name: epgstation_exporter-${{ matrix.os }}-${{ matrix.arch }}
          path: ./epgstation_exporter
  lint:
    name: golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.50'
  release:
    name: release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs:
      - build
      - lint
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [linux]
        arch:
          - amd64
          - arm
          - arm64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: epgstation_exporter-${{ matrix.os }}-${{ matrix.arch }}
      - env:
          GOOS: '${{ matrix.os }}'
          GOARCH: '${{ matrix.arch }}'
        run: |
          name=epgstation_exporter-$(cat VERSION).$GOOS-$GOARCH
          mkdir "$name"
          mv README.md "${name}/"
          chmod +x epgstation_exporter
          mv epgstation_exporter "${name}/"
          tar cf "$name.tar.gz" "$name"
      - uses: softprops/action-gh-release@v1
        with:
          files: epgstation_exporter-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_container_image:
    name: build container image
    if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
    needs:
      - build
      - lint
    runs-on: ubuntu-22.04
    env:
      BIN_DIR: ./dist
      IMAGE_REPOSITORY: ghcr.io/coord-e/epgstation-exporter
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p $BIN_DIR/{amd64,arm64}
      - uses: actions/download-artifact@v3
        with:
          name: epgstation_exporter-linux-amd64
          path: ${{ env.BIN_DIR }}/amd64/
      - uses: actions/download-artifact@v3
        with:
          name: epgstation_exporter-linux-arm64
          path: ${{ env.BIN_DIR }}/arm64/
      - run: chmod +x $BIN_DIR/{amd64,arm64}/*
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: select tags
        id: select-tags
        run: |
          if [ "$GITHUB_REF_TYPE" == tag ]; then
            echo "tags=$IMAGE_REPOSITORY:latest,$IMAGE_REPOSITORY:$(cat VERSION)" >> $GITHUB_OUTPUT
          else
            echo "tags=$IMAGE_REPOSITORY:$GITHUB_SHA,$IMAGE_REPOSITORY:$GITHUB_REF_NAME" >> $GITHUB_OUTPUT
          fi
      - uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.select-tags.outputs.tags }}
          build-args: BIN_DIR
